spring:
  application:
    name: security-practice-oauth2

  security:
    user:
      name: admin
      password: admin
      roles:
      - ADMIN
      - USER
    oauth2:
      client:
        registration:
          #GITHUB LOGIN
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          #GOOGLE LOGIN
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}









